### PR TITLE
feat(frontend): add BNB Smart Chain

### PR DESCRIPTION
**Pull request by boriskubrik**
- Adds BNB Smart Chain to the frontend
- Token switching works
- Quote appears to be buggy on the backend

### CODE REVIEW

**Comment by boriskubrik** [comment]
Getting this error in the console 🧐 

```
query.ts:444 ChainDoesNotSupportContract: Chain "BNB Smart Chain" does not support contract "ensUniversalResolver".

This could be due to any of the following:
- The chain does not have the contract "ensUniversalResolver" configured.

Version: viem@1.9.0
    at getChainContractAddress (http://localhost:5173/node_modules/.vite/deps/chunk-22J53CKA.js?v=f00271f6:1102:11)
    at getEnsName (http://localhost:5173/node_modules/.vite/deps/chunk-PSJTYBOA.js?v=f00271f6:3134:32)
    at Object.getEnsName (http://localhost:5173/node_modules/.vite/deps/chunk-PSJTYBOA.js?v=f00271f6:4840:27)
    at fetchEnsName (http://localhost:5173/node_modules/.vite/deps/chunk-COUTCA2W.js?v=f00271f6:3999:23)
    at Object.queryFn12 [as queryFn] (http://localhost:5173/node_modules/.vite/deps/wagmi.js?v=f00271f6:2216:10)
    at Object.fetchFn [as fn] (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:962:27)
    at run (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:627:31)
    at createRetryer (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:661:5)
    at Query.fetch (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:1001:20)
    at QueryObserver.executeFetch (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:2077:37)
```

**Comment by tommy0x** [comment]
> Getting this error in the console. On the frontend, we're using the contract address from wagmi. 🧐
> 
> ```
> query.ts:444 ChainDoesNotSupportContract: Chain "BNB Smart Chain" does not support contract "ensUniversalResolver".
> 
> This could be due to any of the following:
> - The chain does not have the contract "ensUniversalResolver" configured.
> 
> Version: viem@1.9.0
>     at getChainContractAddress (http://localhost:5173/node_modules/.vite/deps/chunk-22J53CKA.js?v=f00271f6:1102:11)
>     at getEnsName (http://localhost:5173/node_modules/.vite/deps/chunk-PSJTYBOA.js?v=f00271f6:3134:32)
>     at Object.getEnsName (http://localhost:5173/node_modules/.vite/deps/chunk-PSJTYBOA.js?v=f00271f6:4840:27)
>     at fetchEnsName (http://localhost:5173/node_modules/.vite/deps/chunk-COUTCA2W.js?v=f00271f6:3999:23)
>     at Object.queryFn12 [as queryFn] (http://localhost:5173/node_modules/.vite/deps/wagmi.js?v=f00271f6:2216:10)
>     at Object.fetchFn [as fn] (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:962:27)
>     at run (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:627:31)
>     at createRetryer (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:661:5)
>     at Query.fetch (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:1001:20)
>     at QueryObserver.executeFetch (http://localhost:5173/node_modules/.vite/deps/chunk-WIHF4XXA.js?v=f00271f6:2077:37)
> ```

This happens on Arbitrum as well. ENS names aren't supported on these chains yet I think, so the contract for getting it also does not exist.

**Review by tommy0x — APPROVED** [review]

**Comment by immutablegoblin** [comment]
We might be able to manually pass them ENS contract addresses when setting up chains - will investigate.

**Comment by immutablegoblin** [comment]
Don't like that it causes a linebreak :(
image

**Comment by boriskubrik** [comment]
> Don't like that it causes a linebreak :(
> 1Inch just call it "BNB chain":

We grab the names straight from the VIEM object. Can fix this later.

**Pull request merged**
